=== retroandchill/prism/src/Prism.Core/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": [
    "object",
    "null"
  ],
  "properties": {
    "version": {
      "type": "integer"
    },
    "trivia": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "displayName": {
            "type": [
              "string",
              "null"
            ]
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "tokens": {
      "type": "object",
      "properties": {
        "keywords": {
          "type": "array",
          "items": {
            "type": [
              "object",
              "null"
            ],
            "properties": {
              "text": {
                "type": "string"
              },
              "contextual": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "text",
              "name"
            ]
          }
        },
        "punctuations": {
          "type": "array",
          "items": {
            "type": [
              "object",
              "null"
            ],
            "properties": {
              "text": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "text",
              "name"
            ]
          }
        },
        "other": {
          "type": "array",
          "items": {
            "type": [
              "object",
              "null"
            ],
            "properties": {
              "displayName": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "name"
            ]
          }
        },
        "length": {
          "type": "integer"
        }
      },
      "required": [
        "keywords",
        "punctuations",
        "other"
      ]
    },
    "modules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "Node",
              "StructuredTrivia"
            ]
          },
          "nodes": {
            "type": "array",
            "items": {
              "type": [
                "object",
                "null"
              ],
              "properties": {
                "name": {
                  "type": "string"
                },
                "base": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "properties": {
                  "type": "array",
                  "items": {
                    "type": [
                      "object",
                      "null"
                    ],
                    "required": [
                      "$type"
                    ],
                    "anyOf": [
                      {
                        "properties": {
                          "$type": {
                            "const": "item"
                          },
                          "name": {
                            "type": "string"
                          },
                          "type": {
                            "type": "string"
                          },
                          "shape": {
                            "enum": [
                              "single",
                              "optional",
                              "list",
                              "separated_list"
                            ]
                          },
                          "kinds": {
                            "type": "array",
                            "items": {
                              "type": [
                                "string",
                                "null"
                              ]
                            }
                          },
                          "separators": {
                            "type": "array",
                            "items": {
                              "type": [
                                "string",
                                "null"
                              ]
                            }
                          }
                        },
                        "required": [
                          "name",
                          "type",
                          "shape"
                        ]
                      },
                      {
                        "properties": {
                          "$type": {
                            "const": "reference"
                          },
                          "name": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "name"
                        ]
                      },
                      {
                        "properties": {
                          "$type": {
                            "const": "choice"
                          },
                          "choices": {
                            "type": "array",
                            "items": {
                              "$ref": "#/properties/modules/items/properties/nodes/items/properties/properties/items"
                            }
                          }
                        },
                        "required": [
                          "choices"
                        ]
                      },
                      {
                        "properties": {
                          "$type": {
                            "const": "sequence"
                          },
                          "elements": {
                            "type": "array",
                            "items": {
                              "$ref": "#/properties/modules/items/properties/nodes/items/properties/properties/items"
                            }
                          }
                        },
                        "required": [
                          "elements"
                        ]
                      }
                    ]
                  }
                }
              },
              "required": [
                "name"
              ]
            }
          }
        },
        "required": [
          "name",
          "nodes"
        ]
      }
    },
    "diagnostics": {
      "type": "array",
      "items": {
        "type": [
          "object",
          "null"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "diagnostics": {
            "type": "array",
            "items": {
              "type": [
                "object",
                "null"
              ],
              "properties": {
                "name": {
                  "type": "string"
                },
                "severity": {
                  "enum": [
                    "Error",
                    "Warning",
                    "Info",
                    "Hint"
                  ]
                },
                "format": {
                  "type": "string"
                },
                "args": {
                  "type": "array",
                  "items": {
                    "type": [
                      "object",
                      "null"
                    ],
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "type": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "name",
                      "type"
                    ]
                  }
                },
                "explanation": {
                  "type": "string"
                },
                "helpLink": {
                  "type": "string"
                },
                "tags": {
                  "type": "array",
                  "items": {
                    "type": [
                      "string",
                      "null"
                    ]
                  }
                }
              },
              "required": [
                "name",
                "severity",
                "format"
              ]
            }
          }
        },
        "required": [
          "name",
          "diagnostics"
        ]
      }
    }
  },
  "required": [
    "version",
    "trivia",
    "tokens",
    "modules",
    "diagnostics"
  ]
}

=== retroandchill/prism/src/Prism.Core/nodes.json
{
  "$schema": "./schema.json",
  "version": 1,
  "trivia": [
    {
      "name": "WhitespaceTrivia"
    },
    {
      "name": "NewLineTrivia"
    },
    {
      "name": "LineCommentTrivia"
    },
    {
      "name": "BlockCommentTrivia"
    }
  ],
  "tokens": {
    "keywords": [
      {
        "name": "NamespaceKeyword",
        "text": "namespace"
      },
      {
        "name": "UsingKeyword",
        "text": "using"
      },
      {
        "name": "PublicKeyword",
        "text": "public"
      },
      {
        "name": "InternalKeyword",
        "text": "internal"
      },
      {
        "name": "ProtectedKeyword",
        "text": "protected"
      },
      {
        "name": "PrivateKeyword",
        "text": "private"
      },
      {
        "name": "FileKeyword",
        "text": "file",
        "contextual": true
      },
      {
        "name": "VarKeyword",
        "text": "var"
      },
      {
        "name": "ConstKeyword",
        "text": "const"
      },
      {
        "name": "SizeOfKeyword",
        "text": "sizeof"
      },
      {
        "name": "FuncKeyword",
        "text": "func"
      },
      {
        "name": "AttributeKeyword",
        "text": "attribute"
      },
      {
        "name": "ClassKeyword",
        "text": "class"
      },
      {
        "name": "ExternKeyword",
        "text": "extern"
      },
      {
        "name": "StaticKeyword",
        "text": "static"
      },
      {
        "name": "ReturnKeyword",
        "text": "return"
      },
      {
        "name": "MutableKeyword",
        "text": "mutable"
      },
      {
        "name": "AsKeyword",
        "text": "as"
      },
      {
        "name": "IfKeyword",
        "text": "if"
      },
      {
        "name": "ElseKeyword",
        "text": "else"
      },
      {
        "name": "WhileKeyword",
        "text": "while"
      },
      {
        "name": "LoopKeyword",
        "text": "loop"
      },
      {
        "name": "ForKeyword",
        "text": "for"
      },
      {
        "name": "BreakKeyword",
        "text": "break"
      },
      {
        "name": "ContinueKeyword",
        "text": "continue"
      },
      {
        "name": "ValueKeyword",
        "text": "value",
        "contextual": true
      },
      {
        "name": "ThisKeyword",
        "text": "this"
      },
      {
        "name": "NullKeyword",
        "text": "null"
      },
      {
        "name": "TrueKeyword",
        "text": "true"
      },
      {
        "name": "FalseKeyword",
        "text": "false"
      },
      {
        "name": "VoidKeyword",
        "text": "void"
      },
      {
        "name": "BoolKeyword",
        "text": "bool"
      },
      {
        "name": "I8Keyword",
        "text": "i8"
      },
      {
        "name": "I16Keyword",
        "text": "i16"
      },
      {
        "name": "I32Keyword",
        "text": "i32"
      },
      {
        "name": "I64Keyword",
        "text": "i64"
      },
      {
        "name": "I128Keyword",
        "text": "i128"
      },
      {
        "name": "U8Keyword",
        "text": "u8"
      },
      {
        "name": "U16Keyword",
        "text": "u16"
      },
      {
        "name": "U32Keyword",
        "text": "u32"
      },
      {
        "name": "U64Keyword",
        "text": "u64"
      },
      {
        "name": "U128Keyword",
        "text": "u128"
      },
      {
        "name": "IsizeKeyword",
        "text": "isize"
      },
      {
        "name": "UsizeKeyword",
        "text": "usize"
      },
      {
        "name": "F32Keyword",
        "text": "f32"
      },
      {
        "name": "F64Keyword",
        "text": "f64"
      },
      {
        "name": "CharKeyword",
        "text": "char"
      },
      {
        "name": "Char16Keyword",
        "text": "char16"
      },
      {
        "name": "RuneKeyword",
        "text": "rune"
      },
      {
        "name": "StrKeyword",
        "text": "str"
      },
      {
        "name": "ConstructorKeyword",
        "text": "constructor",
        "contextual": true
      },
      {
        "name": "DefaultKeyword",
        "text": "default"
      },
      {
        "name": "NewKeyword",
        "text": "new"
      }
    ],
    "punctuations": [
      {
        "name": "OpenBracketToken",
        "text": "["
      },
      {
        "name": "CloseBracketToken",
        "text": "]"
      },
      {
        "name": "OpenParenToken",
        "text": "("
      },
      {
        "name": "CloseParenToken",
        "text": ")"
      },
      {
        "name": "OpenBraceToken",
        "text": "{"
      },
      {
        "name": "CloseBraceToken",
        "text": "}"
      },
      {
        "name": "PeriodToken",
        "text": "."
      },
      {
        "name": "EllipsisToken",
        "text": "..."
      },
      {
        "name": "AmpToken",
        "text": "&"
      },
      {
        "name": "AmpAmpToken",
        "text": "&&"
      },
      {
        "name": "AmpEqualToken",
        "text": "&="
      },
      {
        "name": "AmpAmpEqualToken",
        "text": "&&="
      },
      {
        "name": "StarToken",
        "text": "*"
      },
      {
        "name": "StarEqualToken",
        "text": "*="
      },
      {
        "name": "PlusToken",
        "text": "+"
      },
      {
        "name": "PlusPlusToken",
        "text": "++"
      },
      {
        "name": "PlusEqualToken",
        "text": "+="
      },
      {
        "name": "MinusToken",
        "text": "-"
      },
      {
        "name": "MinusMinusToken",
        "text": "--"
      },
      {
        "name": "MinusEqualToken",
        "text": "-="
      },
      {
        "name": "TildeToken",
        "text": "~"
      },
      {
        "name": "BangToken",
        "text": "!"
      },
      {
        "name": "BangEqualToken",
        "text": "!="
      },
      {
        "name": "SlashToken",
        "text": "/"
      },
      {
        "name": "SlashEqualToken",
        "text": "/="
      },
      {
        "name": "PercentToken",
        "text": "%"
      },
      {
        "name": "PercentEqualToken",
        "text": "%="
      },
      {
        "name": "LessToken",
        "text": "<"
      },
      {
        "name": "LessLessToken",
        "text": "<<"
      },
      {
        "name": "LessEqualToken",
        "text": "<="
      },
      {
        "name": "LessLessEqualToken",
        "text": "<<="
      },
      {
        "name": "SpaceshipToken",
        "text": "<=>"
      },
      {
        "name": "GreaterToken",
        "text": ">"
      },
      {
        "name": "GreaterGreaterToken",
        "text": ">>"
      },
      {
        "name": "GreaterGreaterGreaterToken",
        "text": ">>>"
      },
      {
        "name": "GreaterEqualToken",
        "text": ">="
      },
      {
        "name": "GreaterGreaterEqualToken",
        "text": ">>="
      },
      {
        "name": "GreaterGreaterGreaterEqualToken",
        "text": ">>>="
      },
      {
        "name": "CaretToken",
        "text": "^"
      },
      {
        "name": "CaretEqualToken",
        "text": "^="
      },
      {
        "name": "PipeToken",
        "text": "|"
      },
      {
        "name": "PipePipeToken",
        "text": "||"
      },
      {
        "name": "PipeEqualToken",
        "text": "|="
      },
      {
        "name": "PipePipeEqualToken",
        "text": "||="
      },
      {
        "name": "QuestionToken",
        "text": "?"
      },
      {
        "name": "QuestionQuestionToken",
        "text": "??"
      },
      {
        "name": "QuestionQuestionEqualToken",
        "text": "??="
      },
      {
        "name": "QuestionPeriodToken",
        "text": "?."
      },
      {
        "name": "ColonToken",
        "text": ":"
      },
      {
        "name": "DoubleColonToken",
        "text": "::"
      },
      {
        "name": "SemicolonToken",
        "text": ";"
      },
      {
        "name": "EqualToken",
        "text": "="
      },
      {
        "name": "ArrowToken",
        "text": "=>"
      },
      {
        "name": "EqualEqualToken",
        "text": "=="
      },
      {
        "name": "CommaToken",
        "text": ","
      }
    ],
    "other": [
      {
        "name": "EofToken",
        "displayName": "EOF"
      },
      {
        "name": "BadToken",
        "displayName": "<unrecognized>"
      },
      {
        "name": "IdentifierToken"
      },
      {
        "name": "IntegerLiteralToken"
      },
      {
        "name": "FloatingPointLiteralToken"
      },
      {
        "name": "CharacterLiteralToken"
      },
      {
        "name": "StringLiteralToken"
      }
    ]
  },
  "modules": [
    {
      "name": "StructuredTrivia",
      "kind": "StructuredTrivia",
      "nodes": [
        {
          "name": "SkippedTokensTrivia",
          "properties": [
            {
              "$type": "item",
              "name": "tokens",
              "type": "Token",
              "shape": "list"
            }
          ]
        }
      ]
    },
    {
      "name": "TopLevel",
      "nodes": [
        {
          "name": "CompilationUnit",
          "properties": [
            {
              "$type": "item",
              "name": "usings",
              "type": "UsingDirective",
              "shape": "list"
            },
            {
              "$type": "item",
              "name": "members",
              "type": "Declaration",
              "shape": "list"
            },
            {
              "$type": "item",
              "name": "eof",
              "type": "Token",
              "shape": "single",
              "kinds": [
                "EofToken"
              ]
            }
          ]
        }
      ]
    },
    {
      "name": "Types",
      "nodes": [
        {
          "name": "Type",
          "properties": []
        },
        {
          "name": "PredefinedType",
          "base": "Type",
          "properties": [
            {
